# Generated by Django 3.0.4 on 2020-03-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectpoint',
            name='itens',
            field=models.CharField(default=1, max_length=255, verbose_name='Itens para Doação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectpoint',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
    ]
